Modify 'web suite' link to be a dropdown menu containing apps
openflighthpc/flight-webapp-components pull request #7
Opened 2022-04-05 12:22 UTC by VoxSecundus

This PR introduces a change to the landing page navbar. The conditionally used `Web Suite` button is now a split dropdown button. The old button functionality remains the same, but it is now followed by a dropdown button listing the available webapps provided to `flight-webapp-components` by the webapp currently being visited.

2022-04-05 12:44 UTC, benarmston commented
@VoxSecundus webapp components (and our webapps in general) are already using [reactstrap](https://deploy-preview-2356--reactstrap.netlify.app/components/button-dropdown/) as the react bootstrap library.  Can you remove the use of `react-bootstrap` and change this to use `reactstrap` please.

2022-04-05 13:01 UTC, VoxSecundus commented
@benarmston I've just updated the branch to use `reactstrap` instead of `react-bootstrap`.

2022-04-11 14:18 UTC, benarmston commented
@VoxSecundus can you rebease this on `origin/master` and then I'll take another look.

```sh
ben@midgard:~/projects/flight-webapp-components (enh/web-suite-dropdown *$% u=)
$ git log  --oneline origin/master --not HEAD
5ee4ab0 (tag: 0.3.0, origin/master, origin/HEAD, master) Merge branch 'release/0.3.0'
3e3c71b Remove old test artefacts
4dc83f4 Bump version to 0.3.0
c2ce982 `./bin/release.sh` learns `--version NEW_VERSION`
c9ba386 Bump .nvmrc
f1937eb Merge pull request #5 from openflighthpc/enh/sign-in-modal-copy
491fa14 Build artefacts
e3e22ac Better form customization
1fe7a14 Add support for importing sign in modal text from branding
6eb0790 Merge pull request #6 from openflighthpc/enh/fold-in-wae-changes
215c584 Build artefacts
e3186b8 Update Footer to have configurable copyright
9e1e0dc Support additional items on brandbar
b4d5498 Fold in WAE branding changes
```

(You'll likely need to do the same for the UMD login widget work).

2022-04-11 14:24 UTC, VoxSecundus commented
Rebased on `master` successfully

2022-04-11 14:50 UTC, benarmston requested changes
This is close.  A `dropdown` class is missing and also some font colour issues with the alces branding.

![image](https://user-images.githubusercontent.com/287050/162766035-e170347a-3ea9-457f-9c71-a91c5b07415c.png)

2022-04-11 14:50 UTC, benarmston commented on src/BrandBar.js
>      <li className="nav-item">
Can you add a `dropdown` class to this please?

2022-04-11 15:17 UTC, VoxSecundus commented
@benarmston I'm not getting the font colour issue on my build; have you made any local changes to the `alces-branding` type?

2022-04-11 17:53 UTC, benarmston requested changes
After following through the flight direct branding dropdown item colour issues, I have some more comments on this PR.  These comments go hand-in-hand with those I've added to https://github.com/openflighthpc/flight-landing-page/pull/16

2022-04-11 17:53 UTC, benarmston commented on src/brandbar.module.css
> +}
This shouldn't be necessary.  If you have the webapp's loading their styles from the dev landing page, they should already be picking up this setting from `branding.css`.

2022-04-11 17:53 UTC, benarmston commented on src/brandbar.module.css
> +  padding: 8px;
This padding isn't wanted.

The landing page `dropdown-item`s incorrectly have the `nav-link nav-menu-button` classes.  The `nav-link` class adds some unwanted `padding: 0.5rem`.  We want the default padding for `.dropdown-item`.  (Or something similar to that.  Either way we should be using the default padding for `.dropdown-item`).

The fix to this is

1. Remove `nav-link nav-menu-button` from `dropdown-item` in flight landing page repo.
2. Remove this padding here.

2022-04-11 17:53 UTC, benarmston commented on src/brandbar.module.css
> +}
These colours aren't going to work with the default (openflight) branding.  Colours such as this should be specified in the `branding.css` files in landing page and picked up by the webapp.

Remove these colours and make the changes to branding.css I've asked for on flight-landing-page.

2022-04-14 11:42 UTC, benarmston commented
LGTM.

2022-04-14 11:42 UTC, merged